# Title of the GitHub repository
repository: reflectivity/reflectivity.github.io

# This appears on the top navigation bar next to the home button
topnav_title: ORSO

# This appears in the html browser tab for the site title (seen mostly by search engines, not users)
site_title: Open Reflectometry Standards Organisation

# Site logo
logo: https://github.com/reflectivity/logo/raw/master/aglavic/ORSO_Logo_clean.png

# The preview server and port used. Leave as is.
host: 127.0.0.1
port: 4000

# These are the files and directories that jekyll will exclude from the build
exclude:
  - .idea/
  - .gitignore
  - vendor

# Library used for code syntax highlighting
highlighter: rouge

# Filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

github: [metadata]
